# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    
    - uses: actions/checkout@v3  
    - name: GitHub Action for flyctl
      # You may pin to the exact commit or the version.
      # uses: superfly/flyctl-actions@0141aba3cab6d573e576ca804ccd870d67aff5ca
      uses: superfly/flyctl-actions@1.1
    - run: flyctl deploy
